export type BlendMode =
  | "PASS_THROUGH"
  | "NORMAL"
  | "DARKEN"
  | "MULTIPLY"
  | "LINEAR_BURN"
  | "COLOR_BURN"
  | "LIGHTEN"
  | "SCREEN"
  | "LINEAR_DODGE"
  | "COLOR_DODGE"
  | "OVERLAY"
  | "SOFT_LIGHT"
  | "HARD_LIGHT"
  | "DIFFERENCE"
  | "EXCLUSION"
  | "HUE"
  | "SATURATION"
  | "COLOR"
  | "LUMINOSITY"
export type ConstraintType = "SCALE" | "WIDTH" | "HEIGHT"
export type EffectType =
  | "INNER_SHADOW"
  | "DROP_SHADOW"
  | "LAYER_BLUR"
  | "BACKGROUND_BLUR"
export type EasingType = "EASE_IN" | "EASE_OUT" | "EASE_IN_AND_OUT"
export type StyleType = "FILL" | "TEXT" | "EFFECT" | "GRID"
export type NodeType =
  | "DOCUMENT"
  | "CANVAS"
  | "FRAME"
  | "INSTANCE"
  | "RECTANGLE"
  | "GROUP"
  | "TEXT"
  | "VECTOR"
  | "BOOLEAN_OPERATION"
  | "STAR"
  | "LINE"
  | "ELLIPSE"
  | "REGULAR_POLYGON"
  | "SLICE"
  | "COMPONENT"
export type ScaleModeType = "FILL" | "FIT" | "TILE" | "STRETCH"
export type PaintType =
  | "SOLID"
  | "GRADIENT_LINEAR"
  | "GRADIENT_RADIAL"
  | "GRADIENT_ANGULAR"
  | "GRADIENT_DIAMOND"
  | "IMAGE"
  | "EMOJI"
export type BooleanOperationType =
  | "UNION"
  | "INTERSECT"
  | "SUBTRACT"
  | "EXCLUDE"
export type StrokeAlignType = "INSIDE" | "OUTSIDE" | "CENTER"
export type StrokeCapType =
  | "NONE"
  | "ROUND"
  | "SQUARE"
  | "LINE_ARROW"
  | "TRIANGLE_ARROW"
export type StrokeJoinType = "MITTER" | "BEVEL" | "ROUND"
export type LayoutConstraintVerticalType =
  | "TOP"
  | "BOTTOM"
  | "CENTER"
  | "TOP_BOTTOM"
  | "SCALE"
export type LayoutConstraintHorizontalType =
  | "LEFT"
  | "RIGHT"
  | "CENTER"
  | "LEFT_RIGHT"
  | "SCALE"
export type LayoutGridPatternType = "COLUMNS" | "ROWS" | "GRID"
export type LayoutGridAlignmentType = "MIN" | "STRETCH" | "CENTER"
export type TextCaseType = "ORIGINAL" | "UPPER" | "LOWER" | "TITLE"
export type TextDecorationType = "NONE" | "STRIKETHROUGH" | "UNDERLINE"
export type TextAlignHorizontalType = "LEFT" | "RIGHT" | "CENTER" | "JUSTIFIED"
export type TextAlignVerticalType = "TOP" | "CENTER" | "BOTTOM"
export type LineHeightUnitType = "PIXELS" | "FONT_SIZE_%" | "INTRINSIC_%"
